# Editable G-code patch rules for A1 Swap Mod Packer.

[swap]
insert_before_marker = ;=====printer finish  sound=========

[patch.a1_start_y]
enabled = true
flag = G0 X128 F30000
find = G0 Y254 F3000
replace = G0 Y250 F3000 ;Patched
max_count = 1
